#!/bin/bash

# GitHub Pages Deployment Instructions
# ====================================

echo "🚀 Nuvora Store - GitHub Pages Deployment Guide"
echo "================================================"
echo ""
echo "Your project is ready for GitHub Pages deployment!"
echo ""
echo "Follow these steps to deploy your site:"
echo ""
echo "1. CREATE GITHUB REPOSITORY:"
echo "   - Go to https://github.com/new"
echo "   - Repository name: nuvora-fakestore"
echo "   - Make it public (required for free GitHub Pages)"
echo "   - Don't initialize with README (we already have one)"
echo "   - Click 'Create repository'"
echo ""
echo "2. CONNECT TO GITHUB (run these commands):"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR_USERNAME/nuvora-fakestore.git"
echo "   git push -u origin main"
echo ""
echo "3. ENABLE GITHUB PAGES:"
echo "   - Go to your repository on GitHub"
echo "   - Click 'Settings' tab"
echo "   - Scroll down to 'Pages' section"
echo "   - Under 'Source', select 'GitHub Actions'"
echo "   - The workflow will automatically deploy your site"
echo ""
echo "4. YOUR SITE WILL BE AVAILABLE AT:"
echo "   https://YOUR_USERNAME.github.io/nuvora-fakestore/"
echo ""
echo "5. IMPORTANT NOTES:"
echo "   - Replace 'YOUR_USERNAME' with your actual GitHub username"
echo "   - The first deployment takes 2-3 minutes"
echo "   - Future deployments happen automatically when you push changes"
echo "   - Check the 'Actions' tab to see deployment status"
echo ""
echo "🎉 That's it! Your e-commerce site will be live!"
echo ""
echo "Need help? Check the README.md file for more details."
