name: Deploy to GitHub Pages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        
        # Add permissions for GitHub Pages deployment
        permissions:
            contents: read
            pages: write
            id-token: write
            deployments: write
            
        # Allow only one concurrent deployment
        concurrency:
            group: "pages"
            cancel-in-progress: false

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure Git to use HTTPS instead of SSH
              run: |
                  git config --global url."https://github.com/".insteadOf "git@github.com:"
                  git config --global url."https://".insteadOf "git://"

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 8

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "pnpm"

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Setup pnpm cache
              uses: actions/cache@v4
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CI: false

            - name: Build
              run: pnpm run build

            - name: Setup Pages
              uses: actions/configure-pages@v5
              if: github.ref == 'refs/heads/main'
              
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              if: github.ref == 'refs/heads/main'
              with:
                  path: ./dist
                  
            - name: Deploy to GitHub Pages
              id: deployment
              if: github.ref == 'refs/heads/main'
              uses: actions/deploy-pages@v4
